Repository authier-pm/authier, pull requests merged in 2023-07, with the labels that each got.

#432 Mobile pricing page
  mobile-app/App.tsx
  mobile-app/src/components/form/CheckBoxField.tsx
  mobile-app/src/components/form/FormComponent.tsx
  mobile-app/src/components/form/PasswordTextField.tsx
  mobile-app/src/components/form/SelectField.tsx
  mobile-app/src/components/form/SelectNumberField.tsx
  mobile-app/src/components/form/TextFiled.tsx
  mobile-app/src/screens/Account/Limits.tsx
  mobile-app/src/screens/Auth/Login.tsx
  mobile-app/src/screens/Auth/LoginAwaitingApproval.tsx
  mobile-app/src/screens/Auth/Register.tsx
  mobile-app/src/screens/VaultUnlockVerification.tsx
  mobile-app/src/utils/tsForm.tsx
  mobile-app/src/utils/useInterval.tsx
Labels: bug, mobile-app, ASAP

#433 handle all the events we need from stripe
  backend/app.ts
  backend/package.json
  backend/stripeWebhook.spec.ts
  backend/stripeWebhook.ts
  pnpm-lock.yaml
Labels: enhancement, api

#434 ensure vault list stays as chosen across all chrome extensions
  Dockerfile
  backend/Dockerfile
  web-extension/src/pages-vault/VaultList.tsx
  web-extension/src/pages-vault/VaultRouter.tsx
  web-extension/src/util/useDeviceState.tsx
Labels: enhancement

#435 Fix WE tests and autofill
  web-extension/package.json
  web-extension/src/PopupRoutes.tsx
  web-extension/src/background/getContentScriptInitialState.ts
  web-extension/src/components/vault/VirtualizedList.tsx
  web-extension/tests/secrets.spec.ts
Labels: bug, web-extenstion

#437 Stop importing device from content script
  backend/models/WebInputElement.ts
  web-extension/src/background/ExtensionDevice.ts
  web-extension/src/background/backgroundSchemas.ts
  web-extension/src/background/chromeRuntimeListener.ts
  web-extension/src/background/getContentScriptInitialState.ts
  web-extension/src/content-script/autofill.ts
  web-extension/src/content-script/components/PromptPassword.tsx
  web-extension/src/content-script/contentScript.ts
  web-extension/src/content-script/renderSaveCredentialsForm.tsx
Labels: bug, enhancement

#440 Fix keyboard input imitation
  .cspell.json
  web-extension/src/content-script/autofill.ts
Labels: bug
